#!/usr/bin/env bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

if [ -z "$DEV_ENV" ]; then
  echo "env var DEV_ENV needs to be present"
  exit 1
fi

# if i just did DEV_ENV=$(pwd) ./run then this is needed for the rest of the
# scripts
export DEV_ENV="$DEV_ENV"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
  echo "ARG: \"$1\""
  if [[ "$1" == "--dry" ]]; then
    dry_run="1"
  else
    grep="$1"
  fi
  shift
done

log() {
  if [[ $dry_run == "1" ]]; then
    echo "[DRY_RUN]: $1"
  else
    echo "$1"
  fi
}

log "RUN: env: $env -- grep: $grep"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS: Use -perm for checking executability
  runs_dir=$(find "$script_dir/installs" -mindepth 1 -maxdepth 1 -type f -perm +111)
else
  # Linux: Use -executable flag
  runs_dir=$(find $script_dir/installs -mindepth 1 -maxdepth 1 -executable)
fi

# TODO: add/modify filtering for preventing unnecessary installations especially for work
for s in $runs_dir; do
  if echo "$s" | grep -vq "$grep"; then
    log "grep \"$grep\" filtered out $s"
    continue
  fi

  log "running script: $s"

  if [[ $dry_run == "0" ]]; then
    $s
  fi
done
