#!/usr/bin/env bash

# Set the environment variable
export DEV_ENV="$HOME/devenv"

# Print the environment variable to verify
echo "DEV_ENV is set to: $DEV_ENV"

# Set the environment variable
export DOTFILES_DIR="$DEV_ENV/dotfiles"

# Print the environment variable to verify
echo "DOTFILES_DIR is set to: $DOTFILES_DIR"

# Run the install script
./install

# Run the stow script
./stow
