#!/usr/bin/env bash
program="llvm"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  #NOTE: LLVM contains Clangd
  brew install $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  else
    echo "Unsupported OS for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
